pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                script {
                   

                    checkout([$class: 'GitSCM', branches: [[name: 'SamarMatoussi']], userRemoteConfigs: [[url: gitHubUrl]]])
                }
            }
        }

    }
}
